{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "artemis.fullname" . }}
  labels:
{{ include "artemis.labels" . | indent 4 }}
data:
  clientPassword: cGFzc3dvcmQK
  clusterPassword: cGFzc3dvcmQK
{{- end }}
