apiVersion: v1
kind: Service
metadata:
  name: artemis-ping
  namespace: artemis
  labels:
{{ include "artemis.labels.live" . | indent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
  selector:
    app.kubernetes.io/name: {{ include "artemis.name" . }}
  sessionAffinity: None
  publishNotReadyAddresses: true
